In [1]:
import os
import json
import pandas as pd
import sqlite3
import numpy as np

In [2]:
with open("employee.json", "r") as obja:
    data_x = json.load(obja)

In [3]:
data_y = data_x['objects']

In [4]:
list_data_y = []

# printing the details of ID 8

In [5]:
ID_eight = data_y[7]

In [6]:
for k,v in ID_eight.items():
    print(k,":", v)

ID : 8
JobTitle : Audiologist
EmailAddress : Michaela_Little1010@yahoo.com
FirstNameLastName : Michaela Little
vaccinated : True

# Converting the json dictionary to Dataframe

In [7]:
df = pd.DataFrame.from_dict(data_y)

In [8]:
df

,ID,JobTitle,EmailAddress,FirstNameLastName,vaccinated
0,1,Designer,Leroy_Yarlett52@guentu.biz,Leroy Yarlett,False
1,2,Webmaster,Julian_Gonzales8496@famism.biz,Julian Gonzales,True
2,3,Paramedic,George_Porter6363@deons.tech,George Porter,False
3,4,IT Support Staff,Penny_Reynolds8665@supunk.biz,Penny Reynolds,False
4,5,Dentist,Gabriel_Upton1432@bungar.biz,Gabriel Upton,True
5,6,Bookkeeper,Rufus_Jeffery8782@mafthy.com,Rufus Jeffery,True
6,7,Restaurant Manager,Harry_Thomas3263@guentu.biz,Harry Thomas,False
7,8,Audiologist,Michaela_Little1010@yahoo.com,Michaela Little,True
8,9,Loan Officer,Mike_Tailor5085@qater.org,Mike Tailor,False
9,10,Assistant Buyer,Angelina_Haines1218@liret.org,Angelina Haines,False
10,11,Pharmacist,Goldie_Oakley4929@nanoff.biz,Goldie Oakley,False
11,12,Global Logistics Supervisor,Sylvia_Marshall5064@vetan.org,Sylvia Marshall,True
12,13,Restaurant Manager,Mike_Vaughn8880@bulaffy.com,Mike Vaughn,True
13,14,Machine Operator,Melinda_Shepherd7534@ubusive.com,Melinda Shepherd,False
14,15,Operator,Doris_Goldsmith6453@famism.biz,Doris Goldsmith,True
15,16,Associate Professor,Chris_Neal8692@typill.biz,Chris Neal,False
16,17,Health Educator,Harry_Chester2240@tonsy.org,Harry Chester,True
17,18,Inspector,Marla_Farrant3348@deons.tech,Marla Farrant,False
18,19,Fabricator,Tania_Kennedy8370@corti.com,Tania Kennedy,False
19,20,Retail Trainee,Bryon_Gibbons5610@corti.com,Bryon Gibbons,False
20,21,Cash Manager,Ivette_Taylor973@extex.org,Ivette Taylor,False
21,22,HR Coordinator,Chadwick_Eaton1419@twace.org,Chadwick Eaton,False
22,23,Webmaster,Chuck_Plumb9701@nickia.com,Chuck Plumb,False
23,24,Steward,Candace_London3099@mafthy.com,Candace London,False
24,25,Investment Advisor,Marvin_Wilde6902@cispeto.com,Marvin Wilde,True
25,26,Doctor,Barry_Taylor950@grannar.com,Barry Taylor,True
26,27,Bellman,Elijah_Harrison3622@bungar.biz,Elijah Harrison,False
27,28,Front Desk Coordinator,Jazmin_Mason8297@gembat.biz,Jazmin Mason,False
28,29,Budget Analyst,Ramon_Whinter4041@elnee.tech,Ramon Whinter,True
29,30,Doctor,Candace_Darcy6235@jiman.org,Candace Darcy,False
30,31,Insurance Broker,Leilani_Rose1103@fuliss.net,Leilani Rose,False
31,32,Software Engineer,Noemi_Miller6490@eirey.tech,Noemi Miller,True
32,33,Lecturer,Alba_Carson2919@typill.biz,Alba Carson,True
33,34,Doctor,Russel_Walter1385@bungar.biz,Russel Walter,True
34,35,Design Engineer,Maia_Kennedy6742@naiker.biz,Maia Kennedy,False
35,36,Physician,Fred_Clifton2086@infotech44.tech,Fred Clifton,False
36,37,Call Center Representative,Alexander_Kennedy1766@mafthy.com,Alexander Kennedy,True
37,38,Systems Administrator,Naomi_Henderson4478@sheye.org,Naomi Henderson,True
38,39,Biologist,Hank_Howard765@liret.org,Hank Howard,False
39,40,Steward,Dorothy_Mackenzie4447@deons.tech,Dorothy Mackenzie,False
40,41,Front Desk Coordinator,Elena_Gregory8402@ubusive.com,Elena Gregory,True
41,42,Production Painter,Helen_Adams3473@guentu.biz,Helen Adams,True
42,43,Software Engineer,Lucas_Brooks385@typill.biz,Lucas Brooks,False
43,44,Cook,Angelina_Ross7491@qater.org,Angelina Ross,True
44,45,Biologist,Remy_Benfield4958@kideod.biz,Remy Benfield,True
45,46,IT Support Staff,Mackenzie_Neal4273@qater.org,Mackenzie Neal,True
46,47,Associate Professor,Janelle_Parker3414@twace.org,Janelle Parker,True
47,48,Treasurer,Matthew_Woodley2830@gembat.biz,Matthew Woodley,True
48,49,Ambulatory Nurse,Anthony_Coleman4896@nanoff.biz,Anthony Coleman,True
49,50,Restaurant Manager,Peyton_Hobson4407@iatim.tech,Peyton Hobson,True

# Storing the header columns in a list

In [9]:
header_cols = list(df.columns)

In [10]:
header_cols

['ID', 'JobTitle', 'EmailAddress', 'FirstNameLastName', 'vaccinated']

# Creating a db and table

In [11]:
con = sqlite3.connect("data.db")

In [12]:
cur = con.cursor()

In [13]:
query = 'CREATE TABLE employee(ID integer, JobTitle text, EmailAddress VARCHAR(320), FirstNameLastName text, vaccinated text )'

In [14]:
cur.execute(query)

# Creating a nested list from the json data

In [15]:
for i in range(len(data_y)):
    list_temp = []
    for k,v in data_y[i].items():
        list_temp.append(v)
    list_data_y.append(list_temp)

In [16]:
list_data_y

[['1', 'Designer', 'Leroy_Yarlett52@guentu.biz', 'Leroy Yarlett', 'False'],
 ['2',
  'Webmaster',
  'Julian_Gonzales8496@famism.biz',
  'Julian Gonzales',
  'True'],
 ['3', 'Paramedic', 'George_Porter6363@deons.tech', 'George Porter', 'False'],
 ['4',
  'IT Support Staff',
  'Penny_Reynolds8665@supunk.biz',
  'Penny Reynolds',
  'False'],
 ['5', 'Dentist', 'Gabriel_Upton1432@bungar.biz', 'Gabriel Upton', 'True'],
 ['6', 'Bookkeeper', 'Rufus_Jeffery8782@mafthy.com', 'Rufus Jeffery', 'True'],
 ['7',
  'Restaurant Manager',
  'Harry_Thomas3263@guentu.biz',
  'Harry Thomas',
  'False'],
 ['8',
  'Audiologist',
  'Michaela_Little1010@yahoo.com',
  'Michaela Little',
  'True'],
 ['9', 'Loan Officer', 'Mike_Tailor5085@qater.org', 'Mike Tailor', 'False'],
 ['10',
  'Assistant Buyer',
  'Angelina_Haines1218@liret.org',
  'Angelina Haines',
  'False'],
 ['11',
  'Pharmacist',
  'Goldie_Oakley4929@nanoff.biz',
  'Goldie Oakley',
  'False'],
 ['12',
  'Global Logistics Supervisor',
  'Sylvia_Marshall5064@vetan.org',
  'Sylvia Marshall',
  'True'],
 ['13',
  'Restaurant Manager',
  'Mike_Vaughn8880@bulaffy.com',
  'Mike Vaughn',
  'True'],
 ['14',
  'Machine Operator',
  'Melinda_Shepherd7534@ubusive.com',
  'Melinda Shepherd',
  'False'],
 ['15',
  'Operator',
  'Doris_Goldsmith6453@famism.biz',
  'Doris Goldsmith',
  'True'],
 ['16',
  'Associate Professor',
  'Chris_Neal8692@typill.biz',
  'Chris Neal',
  'False'],
 ['17',
  'Health Educator',
  'Harry_Chester2240@tonsy.org',
  'Harry Chester',
  'True'],
 ['18', 'Inspector', 'Marla_Farrant3348@deons.tech', 'Marla Farrant', 'False'],
 ['19', 'Fabricator', 'Tania_Kennedy8370@corti.com', 'Tania Kennedy', 'False'],
 ['20',
  'Retail Trainee',
  'Bryon_Gibbons5610@corti.com',
  'Bryon Gibbons',
  'False'],
 ['21',
  'Cash Manager',
  'Ivette_Taylor973@extex.org',
  'Ivette Taylor',
  'False'],
 ['22',
  'HR Coordinator',
  'Chadwick_Eaton1419@twace.org',
  'Chadwick Eaton',
  'False'],
 ['23', 'Webmaster', 'Chuck_Plumb9701@nickia.com', 'Chuck Plumb', 'False'],
 ['24', 'Steward', 'Candace_London3099@mafthy.com', 'Candace London', 'False'],
 ['25',
  'Investment  Advisor',
  'Marvin_Wilde6902@cispeto.com',
  'Marvin Wilde',
  'True'],
 ['26', 'Doctor', 'Barry_Taylor950@grannar.com', 'Barry Taylor', 'True'],
 ['27',
  'Bellman',
  'Elijah_Harrison3622@bungar.biz',
  'Elijah Harrison',
  'False'],
 ['28',
  'Front Desk Coordinator',
  'Jazmin_Mason8297@gembat.biz',
  'Jazmin Mason',
  'False'],
 ['29',
  'Budget Analyst',
  'Ramon_Whinter4041@elnee.tech',
  'Ramon Whinter',
  'True'],
 ['30', 'Doctor', 'Candace_Darcy6235@jiman.org', 'Candace Darcy', 'False'],
 ['31',
  'Insurance Broker',
  'Leilani_Rose1103@fuliss.net',
  'Leilani Rose',
  'False'],
 ['32',
  'Software Engineer',
  'Noemi_Miller6490@eirey.tech',
  'Noemi Miller',
  'True'],
 ['33', 'Lecturer', 'Alba_Carson2919@typill.biz', 'Alba Carson', 'True'],
 ['34', 'Doctor', 'Russel_Walter1385@bungar.biz', 'Russel Walter', 'True'],
 ['35',
  'Design Engineer',
  'Maia_Kennedy6742@naiker.biz',
  'Maia Kennedy',
  'False'],
 ['36',
  'Physician',
  'Fred_Clifton2086@infotech44.tech',
  'Fred Clifton',
  'False'],
 ['37',
  'Call Center Representative',
  'Alexander_Kennedy1766@mafthy.com',
  'Alexander Kennedy',
  'True'],
 ['38',
  'Systems Administrator',
  'Naomi_Henderson4478@sheye.org',
  'Naomi Henderson',
  'True'],
 ['39', 'Biologist', 'Hank_Howard765@liret.org', 'Hank Howard', 'False'],
 ['40',
  'Steward',
  'Dorothy_Mackenzie4447@deons.tech',
  'Dorothy Mackenzie',
  'False'],
 ['41',
  'Front Desk Coordinator',
  'Elena_Gregory8402@ubusive.com',
  'Elena Gregory',
  'True'],
 ['42',
  'Production Painter',
  'Helen_Adams3473@guentu.biz',
  'Helen Adams',
  'True'],
 ['43',
  'Software Engineer',
  'Lucas_Brooks385@typill.biz',
  'Lucas Brooks',
  'False'],
 ['44', 'Cook', 'Angelina_Ross7491@qater.org', 'Angelina Ross', 'True'],
 ['45', 'Biologist', 'Remy_Benfield4958@kideod.biz', 'Remy Benfield', 'True'],
 ['46',
  'IT Support Staff',
  'Mackenzie_Neal4273@qater.org',
  'Mackenzie Neal',
  'True'],
 ['47',
  'Associate Professor',
  'Janelle_Parker3414@twace.org',
  'Janelle Parker',
  'True'],
 ['48',
  'Treasurer',
  'Matthew_Woodley2830@gembat.biz',
  'Matthew Woodley',
  'True'],
 ['49',
  'Ambulatory Nurse',
  'Anthony_Coleman4896@nanoff.biz',
  'Anthony Coleman',
  'True'],
 ['50',
  'Restaurant Manager',
  'Peyton_Hobson4407@iatim.tech',
  'Peyton Hobson',
  'True']]

# Instering the Json data into the db

In [17]:
query = 'INSERT into employee (ID, JobTitle, EmailAddress, FirstNameLastName, vaccinated) VALUES (?, ?, ?, ?, ?)'
for i in range(len(list_data_y)):
    cur.execute(query,list_data_y[i])

In [18]:
query = 'SELECT name from sqlite_master where type = "table"'
cur.execute(query)

In [19]:
list_tables = cur.fetchall()

In [20]:
list_tables

[('employee',)]

In [21]:
query = 'SELECT * FROM employee'

In [22]:
cur.execute(query)

In [23]:
employees = cur.fetchall()

In [24]:
employees

[(1, 'Designer', 'Leroy_Yarlett52@guentu.biz', 'Leroy Yarlett', 'False'),
 (2, 'Webmaster', 'Julian_Gonzales8496@famism.biz', 'Julian Gonzales', 'True'),
 (3, 'Paramedic', 'George_Porter6363@deons.tech', 'George Porter', 'False'),
 (4,
  'IT Support Staff',
  'Penny_Reynolds8665@supunk.biz',
  'Penny Reynolds',
  'False'),
 (5, 'Dentist', 'Gabriel_Upton1432@bungar.biz', 'Gabriel Upton', 'True'),
 (6, 'Bookkeeper', 'Rufus_Jeffery8782@mafthy.com', 'Rufus Jeffery', 'True'),
 (7,
  'Restaurant Manager',
  'Harry_Thomas3263@guentu.biz',
  'Harry Thomas',
  'False'),
 (8,
  'Audiologist',
  'Michaela_Little1010@yahoo.com',
  'Michaela Little',
  'True'),
 (9, 'Loan Officer', 'Mike_Tailor5085@qater.org', 'Mike Tailor', 'False'),
 (10,
  'Assistant Buyer',
  'Angelina_Haines1218@liret.org',
  'Angelina Haines',
  'False'),
 (11, 'Pharmacist', 'Goldie_Oakley4929@nanoff.biz', 'Goldie Oakley', 'False'),
 (12,
  'Global Logistics Supervisor',
  'Sylvia_Marshall5064@vetan.org',
  'Sylvia Marshall',
  'True'),
 (13,
  'Restaurant Manager',
  'Mike_Vaughn8880@bulaffy.com',
  'Mike Vaughn',
  'True'),
 (14,
  'Machine Operator',
  'Melinda_Shepherd7534@ubusive.com',
  'Melinda Shepherd',
  'False'),
 (15, 'Operator', 'Doris_Goldsmith6453@famism.biz', 'Doris Goldsmith', 'True'),
 (16,
  'Associate Professor',
  'Chris_Neal8692@typill.biz',
  'Chris Neal',
  'False'),
 (17,
  'Health Educator',
  'Harry_Chester2240@tonsy.org',
  'Harry Chester',
  'True'),
 (18, 'Inspector', 'Marla_Farrant3348@deons.tech', 'Marla Farrant', 'False'),
 (19, 'Fabricator', 'Tania_Kennedy8370@corti.com', 'Tania Kennedy', 'False'),
 (20,
  'Retail Trainee',
  'Bryon_Gibbons5610@corti.com',
  'Bryon Gibbons',
  'False'),
 (21, 'Cash Manager', 'Ivette_Taylor973@extex.org', 'Ivette Taylor', 'False'),
 (22,
  'HR Coordinator',
  'Chadwick_Eaton1419@twace.org',
  'Chadwick Eaton',
  'False'),
 (23, 'Webmaster', 'Chuck_Plumb9701@nickia.com', 'Chuck Plumb', 'False'),
 (24, 'Steward', 'Candace_London3099@mafthy.com', 'Candace London', 'False'),
 (25,
  'Investment  Advisor',
  'Marvin_Wilde6902@cispeto.com',
  'Marvin Wilde',
  'True'),
 (26, 'Doctor', 'Barry_Taylor950@grannar.com', 'Barry Taylor', 'True'),
 (27, 'Bellman', 'Elijah_Harrison3622@bungar.biz', 'Elijah Harrison', 'False'),
 (28,
  'Front Desk Coordinator',
  'Jazmin_Mason8297@gembat.biz',
  'Jazmin Mason',
  'False'),
 (29,
  'Budget Analyst',
  'Ramon_Whinter4041@elnee.tech',
  'Ramon Whinter',
  'True'),
 (30, 'Doctor', 'Candace_Darcy6235@jiman.org', 'Candace Darcy', 'False'),
 (31,
  'Insurance Broker',
  'Leilani_Rose1103@fuliss.net',
  'Leilani Rose',
  'False'),
 (32,
  'Software Engineer',
  'Noemi_Miller6490@eirey.tech',
  'Noemi Miller',
  'True'),
 (33, 'Lecturer', 'Alba_Carson2919@typill.biz', 'Alba Carson', 'True'),
 (34, 'Doctor', 'Russel_Walter1385@bungar.biz', 'Russel Walter', 'True'),
 (35,
  'Design Engineer',
  'Maia_Kennedy6742@naiker.biz',
  'Maia Kennedy',
  'False'),
 (36,
  'Physician',
  'Fred_Clifton2086@infotech44.tech',
  'Fred Clifton',
  'False'),
 (37,
  'Call Center Representative',
  'Alexander_Kennedy1766@mafthy.com',
  'Alexander Kennedy',
  'True'),
 (38,
  'Systems Administrator',
  'Naomi_Henderson4478@sheye.org',
  'Naomi Henderson',
  'True'),
 (39, 'Biologist', 'Hank_Howard765@liret.org', 'Hank Howard', 'False'),
 (40,
  'Steward',
  'Dorothy_Mackenzie4447@deons.tech',
  'Dorothy Mackenzie',
  'False'),
 (41,
  'Front Desk Coordinator',
  'Elena_Gregory8402@ubusive.com',
  'Elena Gregory',
  'True'),
 (42,
  'Production Painter',
  'Helen_Adams3473@guentu.biz',
  'Helen Adams',
  'True'),
 (43,
  'Software Engineer',
  'Lucas_Brooks385@typill.biz',
  'Lucas Brooks',
  'False'),
 (44, 'Cook', 'Angelina_Ross7491@qater.org', 'Angelina Ross', 'True'),
 (45, 'Biologist', 'Remy_Benfield4958@kideod.biz', 'Remy Benfield', 'True'),
 (46,
  'IT Support Staff',
  'Mackenzie_Neal4273@qater.org',
  'Mackenzie Neal',
  'True'),
 (47,
  'Associate Professor',
  'Janelle_Parker3414@twace.org',
  'Janelle Parker',
  'True'),
 (48,
  'Treasurer',
  'Matthew_Woodley2830@gembat.biz',
  'Matthew Woodley',
  'True'),
 (49,
  'Ambulatory Nurse',
  'Anthony_Coleman4896@nanoff.biz',
  'Anthony Coleman',
  'True'),
 (50,
  'Restaurant Manager',
  'Peyton_Hobson4407@iatim.tech',
  'Peyton Hobson',
  'True')]

# Fetching the data from the database into a dataframe

In [25]:
query = 'SELECT * FROM employee'

dfa = pd.read_sql_query(query, con)

In [26]:
dfa

,ID,JobTitle,EmailAddress,FirstNameLastName,vaccinated
0,1,Designer,Leroy_Yarlett52@guentu.biz,Leroy Yarlett,False
1,2,Webmaster,Julian_Gonzales8496@famism.biz,Julian Gonzales,True
2,3,Paramedic,George_Porter6363@deons.tech,George Porter,False
3,4,IT Support Staff,Penny_Reynolds8665@supunk.biz,Penny Reynolds,False
4,5,Dentist,Gabriel_Upton1432@bungar.biz,Gabriel Upton,True
5,6,Bookkeeper,Rufus_Jeffery8782@mafthy.com,Rufus Jeffery,True
6,7,Restaurant Manager,Harry_Thomas3263@guentu.biz,Harry Thomas,False
7,8,Audiologist,Michaela_Little1010@yahoo.com,Michaela Little,True
8,9,Loan Officer,Mike_Tailor5085@qater.org,Mike Tailor,False
9,10,Assistant Buyer,Angelina_Haines1218@liret.org,Angelina Haines,False
10,11,Pharmacist,Goldie_Oakley4929@nanoff.biz,Goldie Oakley,False
11,12,Global Logistics Supervisor,Sylvia_Marshall5064@vetan.org,Sylvia Marshall,True
12,13,Restaurant Manager,Mike_Vaughn8880@bulaffy.com,Mike Vaughn,True
13,14,Machine Operator,Melinda_Shepherd7534@ubusive.com,Melinda Shepherd,False
14,15,Operator,Doris_Goldsmith6453@famism.biz,Doris Goldsmith,True
15,16,Associate Professor,Chris_Neal8692@typill.biz,Chris Neal,False
16,17,Health Educator,Harry_Chester2240@tonsy.org,Harry Chester,True
17,18,Inspector,Marla_Farrant3348@deons.tech,Marla Farrant,False
18,19,Fabricator,Tania_Kennedy8370@corti.com,Tania Kennedy,False
19,20,Retail Trainee,Bryon_Gibbons5610@corti.com,Bryon Gibbons,False
20,21,Cash Manager,Ivette_Taylor973@extex.org,Ivette Taylor,False
21,22,HR Coordinator,Chadwick_Eaton1419@twace.org,Chadwick Eaton,False
22,23,Webmaster,Chuck_Plumb9701@nickia.com,Chuck Plumb,False
23,24,Steward,Candace_London3099@mafthy.com,Candace London,False
24,25,Investment Advisor,Marvin_Wilde6902@cispeto.com,Marvin Wilde,True
25,26,Doctor,Barry_Taylor950@grannar.com,Barry Taylor,True
26,27,Bellman,Elijah_Harrison3622@bungar.biz,Elijah Harrison,False
27,28,Front Desk Coordinator,Jazmin_Mason8297@gembat.biz,Jazmin Mason,False
28,29,Budget Analyst,Ramon_Whinter4041@elnee.tech,Ramon Whinter,True
29,30,Doctor,Candace_Darcy6235@jiman.org,Candace Darcy,False
30,31,Insurance Broker,Leilani_Rose1103@fuliss.net,Leilani Rose,False
31,32,Software Engineer,Noemi_Miller6490@eirey.tech,Noemi Miller,True
32,33,Lecturer,Alba_Carson2919@typill.biz,Alba Carson,True
33,34,Doctor,Russel_Walter1385@bungar.biz,Russel Walter,True
34,35,Design Engineer,Maia_Kennedy6742@naiker.biz,Maia Kennedy,False
35,36,Physician,Fred_Clifton2086@infotech44.tech,Fred Clifton,False
36,37,Call Center Representative,Alexander_Kennedy1766@mafthy.com,Alexander Kennedy,True
37,38,Systems Administrator,Naomi_Henderson4478@sheye.org,Naomi Henderson,True
38,39,Biologist,Hank_Howard765@liret.org,Hank Howard,False
39,40,Steward,Dorothy_Mackenzie4447@deons.tech,Dorothy Mackenzie,False
40,41,Front Desk Coordinator,Elena_Gregory8402@ubusive.com,Elena Gregory,True
41,42,Production Painter,Helen_Adams3473@guentu.biz,Helen Adams,True
42,43,Software Engineer,Lucas_Brooks385@typill.biz,Lucas Brooks,False
43,44,Cook,Angelina_Ross7491@qater.org,Angelina Ross,True
44,45,Biologist,Remy_Benfield4958@kideod.biz,Remy Benfield,True
45,46,IT Support Staff,Mackenzie_Neal4273@qater.org,Mackenzie Neal,True
46,47,Associate Professor,Janelle_Parker3414@twace.org,Janelle Parker,True
47,48,Treasurer,Matthew_Woodley2830@gembat.biz,Matthew Woodley,True
48,49,Ambulatory Nurse,Anthony_Coleman4896@nanoff.biz,Anthony Coleman,True
49,50,Restaurant Manager,Peyton_Hobson4407@iatim.tech,Peyton Hobson,True

In [27]:
con.close()

# Updating Bonus

In [28]:
def bonus_percent(row):
    if row['vaccinated'] == 'True':
        bonus = 15
    elif row['vaccinated'] == 'False':
        bonus = 5
    return bonus

In [29]:
dfa['bonus percecnt'] = dfa.apply(bonus_percent, axis=1)

In [30]:
dfa

,ID,JobTitle,EmailAddress,FirstNameLastName,vaccinated,bonus percecnt
0,1,Designer,Leroy_Yarlett52@guentu.biz,Leroy Yarlett,False,5
1,2,Webmaster,Julian_Gonzales8496@famism.biz,Julian Gonzales,True,15
2,3,Paramedic,George_Porter6363@deons.tech,George Porter,False,5
3,4,IT Support Staff,Penny_Reynolds8665@supunk.biz,Penny Reynolds,False,5
4,5,Dentist,Gabriel_Upton1432@bungar.biz,Gabriel Upton,True,15
5,6,Bookkeeper,Rufus_Jeffery8782@mafthy.com,Rufus Jeffery,True,15
6,7,Restaurant Manager,Harry_Thomas3263@guentu.biz,Harry Thomas,False,5
7,8,Audiologist,Michaela_Little1010@yahoo.com,Michaela Little,True,15
8,9,Loan Officer,Mike_Tailor5085@qater.org,Mike Tailor,False,5
9,10,Assistant Buyer,Angelina_Haines1218@liret.org,Angelina Haines,False,5
10,11,Pharmacist,Goldie_Oakley4929@nanoff.biz,Goldie Oakley,False,5
11,12,Global Logistics Supervisor,Sylvia_Marshall5064@vetan.org,Sylvia Marshall,True,15
12,13,Restaurant Manager,Mike_Vaughn8880@bulaffy.com,Mike Vaughn,True,15
13,14,Machine Operator,Melinda_Shepherd7534@ubusive.com,Melinda Shepherd,False,5
14,15,Operator,Doris_Goldsmith6453@famism.biz,Doris Goldsmith,True,15
15,16,Associate Professor,Chris_Neal8692@typill.biz,Chris Neal,False,5
16,17,Health Educator,Harry_Chester2240@tonsy.org,Harry Chester,True,15
17,18,Inspector,Marla_Farrant3348@deons.tech,Marla Farrant,False,5
18,19,Fabricator,Tania_Kennedy8370@corti.com,Tania Kennedy,False,5
19,20,Retail Trainee,Bryon_Gibbons5610@corti.com,Bryon Gibbons,False,5
20,21,Cash Manager,Ivette_Taylor973@extex.org,Ivette Taylor,False,5
21,22,HR Coordinator,Chadwick_Eaton1419@twace.org,Chadwick Eaton,False,5
22,23,Webmaster,Chuck_Plumb9701@nickia.com,Chuck Plumb,False,5
23,24,Steward,Candace_London3099@mafthy.com,Candace London,False,5
24,25,Investment Advisor,Marvin_Wilde6902@cispeto.com,Marvin Wilde,True,15
25,26,Doctor,Barry_Taylor950@grannar.com,Barry Taylor,True,15
26,27,Bellman,Elijah_Harrison3622@bungar.biz,Elijah Harrison,False,5
27,28,Front Desk Coordinator,Jazmin_Mason8297@gembat.biz,Jazmin Mason,False,5
28,29,Budget Analyst,Ramon_Whinter4041@elnee.tech,Ramon Whinter,True,15
29,30,Doctor,Candace_Darcy6235@jiman.org,Candace Darcy,False,5
30,31,Insurance Broker,Leilani_Rose1103@fuliss.net,Leilani Rose,False,5
31,32,Software Engineer,Noemi_Miller6490@eirey.tech,Noemi Miller,True,15
32,33,Lecturer,Alba_Carson2919@typill.biz,Alba Carson,True,15
33,34,Doctor,Russel_Walter1385@bungar.biz,Russel Walter,True,15
34,35,Design Engineer,Maia_Kennedy6742@naiker.biz,Maia Kennedy,False,5
35,36,Physician,Fred_Clifton2086@infotech44.tech,Fred Clifton,False,5
36,37,Call Center Representative,Alexander_Kennedy1766@mafthy.com,Alexander Kennedy,True,15
37,38,Systems Administrator,Naomi_Henderson4478@sheye.org,Naomi Henderson,True,15
38,39,Biologist,Hank_Howard765@liret.org,Hank Howard,False,5
39,40,Steward,Dorothy_Mackenzie4447@deons.tech,Dorothy Mackenzie,False,5
40,41,Front Desk Coordinator,Elena_Gregory8402@ubusive.com,Elena Gregory,True,15
41,42,Production Painter,Helen_Adams3473@guentu.biz,Helen Adams,True,15
42,43,Software Engineer,Lucas_Brooks385@typill.biz,Lucas Brooks,False,5
43,44,Cook,Angelina_Ross7491@qater.org,Angelina Ross,True,15
44,45,Biologist,Remy_Benfield4958@kideod.biz,Remy Benfield,True,15
45,46,IT Support Staff,Mackenzie_Neal4273@qater.org,Mackenzie Neal,True,15
46,47,Associate Professor,Janelle_Parker3414@twace.org,Janelle Parker,True,15
47,48,Treasurer,Matthew_Woodley2830@gembat.biz,Matthew Woodley,True,15
48,49,Ambulatory Nurse,Anthony_Coleman4896@nanoff.biz,Anthony Coleman,True,15
49,50,Restaurant Manager,Peyton_Hobson4407@iatim.tech,Peyton Hobson,True,15

In [31]:
dfa.to_excel('employee.xlsx')